const facultyFields = [
  "firstname",
  "lastname",
  "username",
  "phoneNumber",
  "gender",
  "email",
  "secretKey",
  "password",
  "qualification",
  "joiningDate",
  "experience",
  "street",
  "city",
  "state",
  "zipCode",
  "country",
  "emergencyName",
  "emergencyPhone",
  "emergencyRelation",
];

const facultySelectFields = {
    id: true,
    firstname: true,
    lastname: true,
    username: true,
    email: true,
    phoneNumber: true,
    qualification: true,
    joiningDate: true,
    experience: true,
    street: true,
    state: true,
    city: true,
    zipCode: true,
    country: true,
    emergencyName: true,
    emergencyPhone: true,
    emergencyRelation: true,
};
export  {facultySelectFields,facultyFields}